name: my_firstapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Updated dependencies
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  file_picker: ^10.2.0
  permission_handler: ^12.0.1
  flutter_iconpicker: ^4.0.1
  device_info_plus: ^10.1.0
  on_audio_query: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: squid
      fonts:
        - asset: assets/fonts/squid.ttf

    - family: wave
      fonts:
        - asset: assets/fonts/wave.ttf

    - family: yellow
      fonts:
        - asset: assets/fonts/yellow.ttf
    